/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.quickstart;


import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.sink.SinkFunction;
import org.apache.flink.streaming.api.functions.source.SourceFunction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Skeleton for a Flink DataStream Job.
 *
 * <p>For a tutorial how to write a Flink application, check the
 * tutorials and examples on the <a href="https://flink.apache.org">Flink Website</a>.
 *
 * <p>To package your application into a JAR file for execution, run
 * 'mvn clean package' on the command line.
 *
 * <p>If you change the name of the main class (with the public static void main(String[] args))
 * method, change the respective entry in the POM.xml file (simply search for 'mainClass').
 */
/**
 * Flink DataStream Job 示例。
 *
 * <p>本示例程序展示了如何创建一个基本的 Flink DataStream 作业。
 * Flink DataStream API 用于处理连续的数据流。
 *
 * <p>要了解如何编写 Flink 应用程序，请查看 <a href="https://flink.apache.org">Flink 官方网站</a>上的教程和示例。
 *
 * <p>要将应用程序打包成 JAR 文件以便执行，请在命令行中运行 'mvn clean package'。
 *
 * <p>如果更改了主类（包含 public static void main(String[] args) 方法）的名称，
 * 请同时更改 POM.xml 文件中相应的条目（搜索 'mainClass' 即可找到）。
 */
public class DataStreamJob {

    private final static Logger logger = LoggerFactory.getLogger(DataStreamJob.class);


    /**
     * Flink 作业的入口点。
     *
     * @param args 命令行参数（本示例中未使用）。
     * @throws Exception 如果作业执行过程中发生错误。
     */
    public static void main(String[] args) throws Exception {
        logger.info("main  start  ... ");
        // 设置执行环境，这是构建 Flink 应用程序的主要入口点。
        // StreamExecutionEnvironment 用于定义作业的属性、创建数据源以及最终提交作业以执行。
        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        // 禁用自动生成的 UID，以便更好地控制作业的拓扑结构。
        // 在生产环境中，建议为算子手动指定 UID，以便在作业升级或恢复时保持一致性。
        env.getConfig().disableAutoGeneratedUIDs();

        SinkFunction<String> sink = new SinkFunction<String>() {
            @Override
            public void invoke(String value, Context context) throws Exception {
                SinkFunction.super.invoke(value, context);
                logger.info(value);
            }
        };
        // 自定义 SourceFunction，用于生成输入数据流。
        // SourceFunction 是 Flink 中用于创建自定义数据源的接口。
        SourceFunction<Integer> inputSource = new SourceFunction<Integer>() {
            private transient boolean isCancel = false; // 标记数据源是否已被取消

            /**
             * Flink 运行时调用此方法以启动数据源。
             * @param ctx SourceContext 用于发出元素和可选的水印。
             * @throws Exception 如果在数据生成过程中发生错误。
             */
            @Override
            public void run(SourceContext<Integer> ctx) throws Exception {
                Integer i = 0;
                // 循环生成数据，直到数据源被取消。
                while (!isCancel) {
                    i = i + 1;
                    // 发出下一个整数。
                    ctx.collect(i);
                    // 每隔 300 毫秒发出一个数字。
                    Thread.sleep(300);
                }
            }

            /**
             * 当 Flink 作业取消时，调用此方法。
             * 主要用于清理资源和停止数据生成。
             */
            @Override
            public void cancel() {
                isCancel = true;
            }
        };

        // 将自定义数据源添加到执行环境中。
        // .uid() 和 .name() 方法用于为算子指定唯一的 ID 和名称，这对于作业监控和管理非常有用。
        env.addSource(inputSource)
                .uid("SourceUID") // 为 Source 算子设置唯一 ID
                .name("SourceName") // 为 Source 算子设置名称
                // 对输入流中的每个元素应用 Map 转换。
                // MapFunction 将每个整数转换为一个字符串，前缀为 "A"。
                .map(new MapFunction<Integer, String>() {
                    /**
                     * 对输入值进行转换。
                     * @param value 输入的整数。
                     * @return 转换后的字符串。
                     * @throws Exception 如果转换过程中发生错误。
                     */
                    @Override
                    public String map(Integer value) throws Exception {
                        return "A" + value.toString();
                    }
                })
                .uid("MapUID") // 为 Map 算子设置唯一 ID
                .name("MapName") // 为 Map 算子设置名称
                // 将转换后的数据流发送到自定义的 SinkFunction。
                // SinkFunction 用于定义数据输出的目的地，例如打印到控制台、写入文件或发送到消息队列。
                // 在这个例子中，SinkFunction 只是将接收到的字符串打印到日志中。
                .addSink(sink)
                .uid("SinkUID") // 为 Sink 算子设置唯一 ID
                .name("SinkName"); // 为 Sink 算子设置名称

        /*
         * Here, you can start creating your execution plan for Flink.
         *
         * Start with getting some data from the environment, like
         * 	env.fromSequence(1, 10);
         *
         * then, transform the resulting DataStream<Long> using operations
         * like
         * 	.filter()
         * 	.flatMap()
         * 	.window()
         * 	.process()
         *
         * and many more.
         * Have a look at the programming guide:
         *
         * https://nightlies.apache.org/flink/flink-docs-stable/
         *
         */

        // 执行 Flink 作业。
        // "Flink Java API Skeleton" 是作业的名称，会显示在 Flink 的仪表盘上。
        // 这个调用会阻塞，直到作业完成或被取消。
        // 在调用 execute() 之后，Flink 会将作业的计算图提交给 JobManager 执行。
        env.execute("Flink Java API Skeleton");
        logger.info("Flink Java API Skeleton end ");
    }
}
